services:
  - type: web
    name: nhl-predictor
    env: python
    plan: free
    region: ohio
    buildCommand: ""
    startCommand: python server.py

  - type: cron
    name: nhl-predictor-daily-build
    env: python
    schedule: "0 9 * * *"   # 09:00 UTC ≈ 3:00am Central
    buildCommand: ""
    startCommand: python generate_daily.py
