services:
  - type: web
    name: nhl-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -w 2 -k gthread --threads 8 -t 120 -b 0.0.0.0:$PORT
    envVars:
      - key: REFRESH_TOKEN
        sync: false   # set this in Render Dashboard → Environment
